# Generated by Django 3.1.7 on 2021-07-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_software_technical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='url',
        ),
        migrations.AddField(
            model_name='work',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GITHUB'),
        ),
        migrations.AddField(
            model_name='work',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='リンク'),
        ),
    ]
