# Generated by Django 3.1.7 on 2021-07-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210711_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='イメージ画像'),
        ),
    ]
